name: 'nyc_taxi_dbt'
version: '1.0.0'
config-version: 2

profile: 'nyc_taxi_dbt'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_taxi_dbt:
    bronze:
      +materialized: view
      +schema: TAXIS 
      +tags: ["bronze"]
    
    silver:
      +materialized: view
      +schema: SILVER
      +tags: ["silver"]

    gold:
      +materialized: view
      +schema: GOLD
      +tags: ["gold"]